[build]
  base = "./public"  # Set the base directory to the 'public' folder
  publish = "."       # Set the publish directory to the root directory

[build.environment]
  NODE_VERSION = "20.10.0"  # Specify your Node.js version if needed
